"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-07-14 01:14:38.378174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Enable pgvector now — vector features arrive in a later phase
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name_en', sa.String(length=100), nullable=False),
    sa.Column('name_hi', sa.String(length=100), nullable=False),
    sa.Column('name_mr', sa.String(length=100), nullable=False),
    sa.Column('manager_employee_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['manager_employee_id'], ['employees.id'], name='fk_departments_manager', use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('otp_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('purpose', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_attempts_phone'), 'otp_attempts', ['phone'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('label_en', sa.String(length=100), nullable=False),
    sa.Column('label_hi', sa.String(length=100), nullable=False),
    sa.Column('label_mr', sa.String(length=100), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('factory_lat', sa.Float(), nullable=False),
    sa.Column('factory_lng', sa.Float(), nullable=False),
    sa.Column('radius_meters', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shifts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('ble_beacons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('beacon_uuid', sa.String(length=100), nullable=False),
    sa.Column('major', sa.Integer(), nullable=False),
    sa.Column('minor', sa.Integer(), nullable=False),
    sa.Column('zone_label_en', sa.String(length=100), nullable=False),
    sa.Column('zone_label_hi', sa.String(length=100), nullable=False),
    sa.Column('zone_label_mr', sa.String(length=100), nullable=False),
    sa.Column('department_code', sa.String(length=30), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_code'], ['departments.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employees',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('emp_id', sa.String(length=20), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('department_code', sa.String(length=30), nullable=False),
    sa.Column('designation', sa.String(length=200), nullable=False),
    sa.Column('role_code', sa.String(length=20), nullable=False),
    sa.Column('language_pref', sa.String(length=5), nullable=False),
    sa.Column('shift_swap_eligible', sa.Boolean(), nullable=False),
    sa.Column('onboarding_status', sa.Enum('seeded', 'self_registered', 'pending_approval', 'approved', 'rejected', name='onboarding_status'), nullable=False),
    sa.Column('selfie_url', sa.String(length=500), nullable=True),
    sa.Column('expo_push_token', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_code'], ['departments.code'], ),
    sa.ForeignKeyConstraint(['role_code'], ['roles.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('emp_id'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('form_definitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('department_code', sa.String(length=30), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('title_en', sa.String(length=200), nullable=False),
    sa.Column('title_hi', sa.String(length=200), nullable=False),
    sa.Column('title_mr', sa.String(length=200), nullable=False),
    sa.Column('schema_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('approval_role_code', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_code'], ['departments.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('department_code', 'code', name='uq_form_dept_code')
    )
    op.create_table('attendance',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('punch_in_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('punch_out_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gps_lat', sa.Float(), nullable=True),
    sa.Column('gps_lng', sa.Float(), nullable=True),
    sa.Column('gps_verified', sa.Boolean(), nullable=False),
    sa.Column('ble_beacon_id', sa.String(length=100), nullable=True),
    sa.Column('ble_zone', sa.String(length=100), nullable=True),
    sa.Column('selfie_key', sa.String(length=500), nullable=False),
    sa.Column('verification_level', sa.Enum('verified_plus', 'verified', 'flagged', name='verification_level'), nullable=False),
    sa.Column('shift_code', sa.String(length=10), nullable=True),
    sa.Column('is_late', sa.Boolean(), nullable=False),
    sa.Column('flagged_reason', sa.String(length=200), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['shift_code'], ['shifts.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'date', name='uq_attendance_emp_date')
    )
    op.create_index(op.f('ix_attendance_employee_id'), 'attendance', ['employee_id'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.String(length=60), nullable=True),
    sa.Column('detail_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_table('form_submissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('form_definition_id', sa.UUID(), nullable=False),
    sa.Column('form_version', sa.Integer(), nullable=False),
    sa.Column('submitted_by', sa.UUID(), nullable=False),
    sa.Column('department_code', sa.String(length=30), nullable=False),
    sa.Column('data_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('photos', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('gps_lat', sa.Float(), nullable=True),
    sa.Column('gps_lng', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('submitted', 'approved', 'rejected', 'escalated', name='submission_status'), nullable=False),
    sa.Column('approver_id', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('escalated_to', sa.UUID(), nullable=True),
    sa.Column('escalated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approver_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['department_code'], ['departments.code'], ),
    sa.ForeignKeyConstraint(['escalated_to'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['form_definition_id'], ['form_definitions.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incidents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reported_by', sa.UUID(), nullable=False),
    sa.Column('department_code', sa.String(length=30), nullable=False),
    sa.Column('category', sa.Enum('safety', 'fire', 'machine_breakdown', 'injury', 'electrical', 'water_leakage', 'security', 'other', name='incident_category'), nullable=False),
    sa.Column('photo_key', sa.String(length=500), nullable=False),
    sa.Column('gps_lat', sa.Float(), nullable=True),
    sa.Column('gps_lng', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('voice_note_key', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('submitted', 'seen', 'in_progress', 'resolved', 'escalated', name='incident_status'), nullable=False),
    sa.Column('severity', sa.Enum('normal', 'high', 'critical', name='incident_severity'), nullable=False),
    sa.Column('assigned_manager_id', sa.UUID(), nullable=True),
    sa.Column('escalated_to', sa.UUID(), nullable=True),
    sa.Column('escalated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_manager_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['department_code'], ['departments.code'], ),
    sa.ForeignKeyConstraint(['escalated_to'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['reported_by'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recipient_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('title_en', sa.String(length=200), nullable=False),
    sa.Column('title_hi', sa.String(length=200), nullable=False),
    sa.Column('title_mr', sa.String(length=200), nullable=False),
    sa.Column('body_en', sa.Text(), nullable=False),
    sa.Column('body_hi', sa.Text(), nullable=False),
    sa.Column('body_mr', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=True),
    sa.Column('entity_id', sa.String(length=60), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_recipient_id'), 'notifications', ['recipient_id'], unique=False)
    op.create_table('shift_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('shift_code', sa.String(length=10), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('source', sa.Enum('baseline', 'swap', name='assignment_source'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['shift_code'], ['shifts.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'effective_date', 'source', name='uq_shift_assignment')
    )
    op.create_index(op.f('ix_shift_assignments_employee_id'), 'shift_assignments', ['employee_id'], unique=False)
    op.create_table('shift_swap_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('requester_id', sa.UUID(), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('swap_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('pending_target', 'pending_manager', 'approved', 'rejected', 'cancelled', name='swap_status'), nullable=False),
    sa.Column('target_responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('manager_id', sa.UUID(), nullable=True),
    sa.Column('manager_responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incident_timeline',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('event', sa.String(length=30), nullable=False),
    sa.Column('detail_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_timeline_incident_id'), 'incident_timeline', ['incident_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incident_timeline_incident_id'), table_name='incident_timeline')
    op.drop_table('incident_timeline')
    op.drop_table('shift_swap_requests')
    op.drop_index(op.f('ix_shift_assignments_employee_id'), table_name='shift_assignments')
    op.drop_table('shift_assignments')
    op.drop_index(op.f('ix_notifications_recipient_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('incidents')
    op.drop_table('form_submissions')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_attendance_employee_id'), table_name='attendance')
    op.drop_table('attendance')
    op.drop_table('form_definitions')
    op.drop_table('employees')
    op.drop_table('ble_beacons')
    op.drop_table('shifts')
    op.drop_table('settings')
    op.drop_table('roles')
    op.drop_index(op.f('ix_otp_attempts_phone'), table_name='otp_attempts')
    op.drop_table('otp_attempts')
    op.drop_table('departments')
    # ### end Alembic commands ###
