"""Nightly factory report PDF (fpdf2 + bundled Noto Sans Devanagari, text shaping ON).

fpdf2 with uharfbuzz shaping renders Devanagari conjuncts/matras correctly —
this replaces WeasyPrint (needs fragile system pango/cairo libs) and plain
ReportLab (no OpenType shaping, the #1 Devanagari failure mode).
"""
from datetime import date as date_type
from pathlib import Path

from fpdf import FPDF

FONT_DIR = Path(__file__).resolve().parent.parent / "assets" / "fonts"

L = {
    "en": {
        "title": "Daily Factory Report",
        "date": "Date",
        "attendance": "Attendance by Department",
        "dept": "Department",
        "present": "Present",
        "late": "Late",
        "flagged": "Flagged",
        "submissions": "Form Submissions",
        "count": "Count",
        "incidents": "Incidents",
        "opened": "Opened",
        "resolved": "Resolved",
        "critical": "Critical incidents",
        "none": "None",
        "approvals": "Pending Approvals (aging)",
        "manager": "Manager",
        "pending": "Pending",
        "oldest": "Oldest (days)",
        "unassigned": "— (routes to CGM)",
        "generated": "Generated by Hogo Plus",
    },
    "mr": {
        "title": "दैनिक कारखाना अहवाल",
        "date": "दिनांक",
        "attendance": "विभागानुसार हजेरी",
        "dept": "विभाग",
        "present": "उपस्थित",
        "late": "उशिरा",
        "flagged": "चिन्हांकित",
        "submissions": "फॉर्म सादरीकरणे",
        "count": "संख्या",
        "incidents": "घटना",
        "opened": "नोंदवल्या",
        "resolved": "सोडवल्या",
        "critical": "गंभीर घटना",
        "none": "काही नाही",
        "approvals": "प्रलंबित मंजुऱ्या (कालावधी)",
        "manager": "व्यवस्थापक",
        "pending": "प्रलंबित",
        "oldest": "सर्वात जुनी (दिवस)",
        "unassigned": "— (CGM कडे जाते)",
        "generated": "होगो प्लस द्वारे तयार",
    },
    "hi": {
        "title": "दैनिक कारखाना रिपोर्ट",
        "date": "दिनांक",
        "attendance": "विभाग अनुसार उपस्थिति",
        "dept": "विभाग",
        "present": "उपस्थित",
        "late": "देर से",
        "flagged": "चिह्नित",
        "submissions": "फॉर्म सबमिशन",
        "count": "संख्या",
        "incidents": "घटनाएँ",
        "opened": "दर्ज",
        "resolved": "हल हुईं",
        "critical": "गंभीर घटनाएँ",
        "none": "कोई नहीं",
        "approvals": "लंबित अनुमोदन (अवधि)",
        "manager": "प्रबंधक",
        "pending": "लंबित",
        "oldest": "सबसे पुरानी (दिन)",
        "unassigned": "— (CGM के पास)",
        "generated": "होगो प्लस द्वारा निर्मित",
    },
}


class ReportPDF(FPDF):
    def __init__(self) -> None:
        super().__init__(format="A4")
        self.add_font("NotoDeva", "", str(FONT_DIR / "NotoSansDevanagari-Regular.ttf"))
        self.add_font("NotoDeva", "B", str(FONT_DIR / "NotoSansDevanagari-Bold.ttf"))
        self.add_font("NotoLatin", "", str(FONT_DIR / "NotoSans-Regular.ttf"))
        self.add_font("NotoLatin", "B", str(FONT_DIR / "NotoSans-Bold.ttf"))
        self.set_text_shaping(True)  # critical: proper Devanagari conjunct/matra rendering
        # the Devanagari build lacks Latin letters — fall back to Noto Sans for them
        self.set_fallback_fonts(["NotoLatin"])
        self.set_auto_page_break(auto=True, margin=18)


def _table(pdf: ReportPDF, headers: list[str], rows: list[list[str]], widths: list[int]) -> None:
    pdf.set_font("NotoDeva", "B", 10)
    pdf.set_fill_color(11, 79, 108)
    pdf.set_text_color(255, 255, 255)
    for h, w in zip(headers, widths):
        pdf.cell(w, 8, h, border=1, fill=True)
    pdf.ln()
    pdf.set_font("NotoDeva", "", 10)
    pdf.set_text_color(40, 37, 29)
    fill = False
    for row in rows:
        pdf.set_fill_color(244, 243, 238)
        for v, w in zip(row, widths):
            pdf.cell(w, 8, str(v), border=1, fill=fill)
        pdf.ln()
        fill = not fill
    pdf.ln(4)


def _section(pdf: ReportPDF, title: str) -> None:
    pdf.set_font("NotoDeva", "B", 13)
    pdf.set_text_color(11, 79, 108)
    pdf.cell(0, 10, title)
    pdf.ln(11)


def generate_report_pdf(data: dict, lang: str) -> bytes:
    """data: {date, attendance:[{dept,present,late,flagged}], submissions:[{dept,count}],
    incidents:{opened,resolved,critical:[{category,dept}]},
    approvals:[{dept,manager,count,oldest_days}]}
    Department rows carry pre-localized names in data (name per lang)."""
    t = L.get(lang, L["en"])
    pdf = ReportPDF()
    pdf.add_page()

    pdf.set_font("NotoDeva", "B", 18)
    pdf.set_text_color(11, 79, 108)
    pdf.cell(0, 12, t["title"])
    pdf.ln(12)
    pdf.set_font("NotoDeva", "", 11)
    pdf.set_text_color(90, 90, 90)
    pdf.cell(0, 8, f"{t['date']}: {data['date']}")
    pdf.ln(12)

    _section(pdf, t["attendance"])
    _table(
        pdf,
        [t["dept"], t["present"], t["late"], t["flagged"]],
        [[r["dept"], r["present"], r["late"], r["flagged"]] for r in data["attendance"]],
        [80, 35, 35, 35],
    )

    _section(pdf, t["submissions"])
    _table(
        pdf,
        [t["dept"], t["count"]],
        [[r["dept"], r["count"]] for r in data["submissions"]],
        [80, 35],
    )

    _section(pdf, t["incidents"])
    _table(
        pdf,
        [t["opened"], t["resolved"]],
        [[data["incidents"]["opened"], data["incidents"]["resolved"]]],
        [45, 45],
    )
    pdf.set_font("NotoDeva", "B", 11)
    pdf.set_text_color(232, 90, 111)
    crit = data["incidents"]["critical"]
    pdf.cell(0, 8, f"{t['critical']}: {len(crit) if crit else 0}")
    pdf.ln(9)
    pdf.set_font("NotoDeva", "", 10)
    pdf.set_text_color(40, 37, 29)
    if crit:
        for c in crit:
            pdf.cell(0, 7, f"• {c['category']} — {c['dept']}")
            pdf.ln(7)
    else:
        pdf.cell(0, 7, t["none"])
        pdf.ln(7)
    pdf.ln(4)

    _section(pdf, t["approvals"])
    if data["approvals"]:
        _table(
            pdf,
            [t["dept"], t["manager"], t["pending"], t["oldest"]],
            [
                [r["dept"], r["manager"] or t["unassigned"], r["count"], r["oldest_days"]]
                for r in data["approvals"]
            ],
            [55, 65, 30, 35],
        )
    else:
        pdf.set_font("NotoDeva", "", 10)
        pdf.cell(0, 7, t["none"])
        pdf.ln(10)

    pdf.set_font("NotoDeva", "", 8)
    pdf.set_text_color(150, 150, 150)
    pdf.cell(0, 6, f"{t['generated']} · {date_type.today().isoformat()}")

    return bytes(pdf.output())
